### ISSUE TITLE
Trackpad ok ,Wi-Fi  OK.

### ISSUE THREAD

**Issue by adocode** [Kunqa/Dell-3576-MacOS-Mojave-i5-8250u#2]
macOS-Mojave-10.14.3 
https://blog.daliansky.net/macOS-Mojave-10.14.3-18D42-official-version-with-Clover-4859-original-image.html

Wi-Fi replace dw1707    ok
Trackpad gestures   ok

**Comment by Kunqa** [comment]
> macOS-Mojave-10.14.3
> https://blog.daliansky.net/macOS-Mojave-10.14.3-18D42-official-version-with-Clover-4859-original-image.html
> 
> Wi-Fi replace dw1707 ok
> Trackpad gestures ok

Can u help with trackpad ?
